{% set name = "gst-python" %}
{% set version = "1.18.2" %}
{% set sha256 = "e19d0f760b353e88161b3712193cffbd79bf1314418da792b5fec4d8ecef389c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    # see https://gitlab.freedesktop.org/gstreamer/gst-python/-/merge_requests/41
    - 3e752ede7ed6261681ef3831bc3dbb594f189e76.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # These dependencies are only for cos7 platforms
    - {{ cdt('libglvnd-glx') }}          # [linux & (ppc64le | aarch64)]
    - {{ cdt('libglvnd') }}              # [linux & (ppc64le | aarch64)]
    - {{ cdt('libxshmfence-devel') }}    # [linux & (ppc64le | aarch64)]
    - {{ cdt('mesa-khr-devel') }}        # [linux & (ppc64le | aarch64)]
    # expat here is _only_ required for mesa-dri-drivers
    - {{ cdt('expat') }}                 # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - pkg-config
    - meson
    # see https://github.com/mesonbuild/meson/issues/7611
    - meson !=0.56.*  # [win]
    - ninja
  host:
    - gstreamer
    - gst-plugins-base
    - glib
    - libxcb                             # [linux]
    - python
    - pygobject
  run:
    - {{ pin_compatible('gstreamer') }}
    - {{ pin_compatible('gst-plugins-base') }}
    - python
    - pygobject

test:
  commands:
    - test -f $PREFIX/lib/gstreamer-1.0/libgstpython${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstpython.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin python

about:
  home: http://gstreamer.freedesktop.org/modules/gst-python.html
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-python
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GStreamer Python binding overrides
  description: GStreamer Python binding overrides

extra:
  recipe-maintainers:
    - duncanmmacleod
    - tschoonj
