{% set name = "gst-python" %}
{% set version = "1.14.4" %}
{% set sha256 = "d0fdb24f93b6d889f309d2f526b8ea9577e0084ff0a62b4623ef1aed52e85a1b" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://gstreamer.freedesktop.org/src/{{ name }}/{{ name }}-{{ version }}.tar.xz"
  sha256: "{{ sha256 }}"
  patches:
    - python-ldflags.patch  # [osx and py>=30 and py<38]
    # for python3.8 and above, just use -lpython3.8
    - python-libs-3.8.patch  # [py>=38]

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [unix]
    - pkg-config  # [unix]
  host:
    - glib
    - gstreamer {{ version }}
    - pygobject
    - python
  run:
    - glib
    - pygobject
    - python

test:
  imports:
    - gi.repository.Gst
  commands:
    - python -c "import gi; gi.require_version('Gst', '1.0')"

about:
  home: "http://gstreamer.freedesktop.org/modules/gst-python.html"
  dev_url: "https://gitlab.freedesktop.org/gstreamer/gst-python"
  license: "LGPL-2.1-or-later"
  license_family: "LGPL"
  license_file: "COPYING"
  summary: "GStreamer Python binding overrides"
  description: "GStreamer Python binding overrides"

extra:
  recipe-maintainers:
    - duncanmmacleod
