# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "X6G7uiBgt6oVhclQkzi9yFM9pq6TY3ZDIaXJ9mBd0OVMre6+s+Ue9q6vKcKz0D3wHc1iVfttaq51qlQfFLWgqddQHnn+af0Z5Pqz+Tx+qLpAToSyLMsCCKqCyQ+RgPGn2kK8+vYQPe4XFZ/iVXAxn5TYxpRItcq42rZXceqgrQH5aVi/NtFXq57lhAnMmZUZKWzpLqps7yOU2TZI/J+iXsbk6Fs7AJ/FKNnUxvuHU9CR+rqgH6GRHkiZ55VNIaS7JMTZ0ys/cRwgTdfKV2+eQzsQLlMPSvSR1tVyDCiGFVGaWY7pcvSn/rV8/PHdMzk2AoMEsQ17Xs3Yb7Yt9r/wDp4bmNLa0xmiwJs769uklIqsmK2ri4FIYXM0fNUBzH+EO2I7xYEiYGMsWB+smK42yDrNevzSHTIq8riVhyGxVTUjW599Tv5ymNgR7snNawbVO0zBrQqJzofwNyo0/Oya3VHaqvrkCtil3+KshMDMQkZqx4kpMs+yA/hS2lmZfO+21uEfXAcGd1TQiyJsvwGAiodgfTRCvtAqe/rLgfEjFdOPhYrg4RDWYDrwU7JJ+zo9NyfMQzRZeUwRzqqeEmlkZcQYw5mFlkvMnArtj8F0KMD79WMqiBpTF+Zi6ek+jnedr6eWFaVgHJLlr2qxulFwp2FvmR8l5cAzhybMvMiAzTY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml