travis:
  secure:
    BINSTAR_TOKEN: lrdib6bHkMhBTSBMor1k3Ak2KmBLIrQDKYUtmWeacF+0DvympnPZtZzs0KCPL88+k/uU4CNNyzAPRXJCAlQ1EW9+c4L+QrMnxHF8jfShzJJn1SrGIBz0OgiD6JGiFHlzNVte6vZBTqAs6jQzsf7wgASCJqhCGfV87F2G1/a9YDeTz++iLxKRzzLRVJLrhgEkqWcTMngVLzjKsmSzBUrComOSrQpJPrHid8HRHA1qwxSKJ5JgQuEi5j9XO+pZ8xZjzQFLE8syq2xeFD3LLDRpRb56KgUr/6MvLcENobg+A/CV0ojxaGIsvuc3ED/CJ1wnBXAW17ORHFalWvfkff4NjCFlQTHs6E5DA6V0VGDsc6fKM/weoeCsnRQS/a6oMcpvPat461Ru5+CkKKYAlx77Gf9RVediF9FMtdN/uRRC7AiAqHDlWCOhOT3EoBgh0XQegDYp8cMLEe1ATd7lyTK3K4+0MzjofXng5ICFtKnCZ51g8qBsHS1ZMdt1j5ZpFcAT5ga1SZH1WNQc+FJT3scI2kwQ7/PCd3DxZzEJRVyEnS0jVkChisoYa+mJIfCLSDNWVdLfNqPXbvGF0M+kfKQKYdXMzTNCMwFuoNp2KU/Wf/0BwK1KX2VQUG5aphO9VkwwfpGib/kh+zFBFmLKBSKLEDyn1Y628c6W5WwCHcgklOA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
