travis:
  secure:
    BINSTAR_TOKEN: X6G7uiBgt6oVhclQkzi9yFM9pq6TY3ZDIaXJ9mBd0OVMre6+s+Ue9q6vKcKz0D3wHc1iVfttaq51qlQfFLWgqddQHnn+af0Z5Pqz+Tx+qLpAToSyLMsCCKqCyQ+RgPGn2kK8+vYQPe4XFZ/iVXAxn5TYxpRItcq42rZXceqgrQH5aVi/NtFXq57lhAnMmZUZKWzpLqps7yOU2TZI/J+iXsbk6Fs7AJ/FKNnUxvuHU9CR+rqgH6GRHkiZ55VNIaS7JMTZ0ys/cRwgTdfKV2+eQzsQLlMPSvSR1tVyDCiGFVGaWY7pcvSn/rV8/PHdMzk2AoMEsQ17Xs3Yb7Yt9r/wDp4bmNLa0xmiwJs769uklIqsmK2ri4FIYXM0fNUBzH+EO2I7xYEiYGMsWB+smK42yDrNevzSHTIq8riVhyGxVTUjW599Tv5ymNgR7snNawbVO0zBrQqJzofwNyo0/Oya3VHaqvrkCtil3+KshMDMQkZqx4kpMs+yA/hS2lmZfO+21uEfXAcGd1TQiyJsvwGAiodgfTRCvtAqe/rLgfEjFdOPhYrg4RDWYDrwU7JJ+zo9NyfMQzRZeUwRzqqeEmlkZcQYw5mFlkvMnArtj8F0KMD79WMqiBpTF+Zi6ek+jnedr6eWFaVgHJLlr2qxulFwp2FvmR8l5cAzhybMvMiAzTY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
